# Tuple

###`Q1:` Join Tuples if similar initial element
While working with Python tuples, we can have a problem in which we need to perform concatenation of records from the similarity of initial element. This problem can have applications in data domains such as Data Science.

For eg.
```
Input  : test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]
Output : [(5, 6, 7, 8), (6, 10), (7, 13)]
```

In [ ]:
# write your code here
test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]
temp_list = []
for a,b in test_list[:3]:
  if a not in temp_list:
    temp_list.append(a)
  if b not in temp_list:
    temp_list.append(b)
  test_list.pop(0)
t=tuple(temp_list)
test_list.insert(0,0)
test_list[0]=t
print(test_list)

[(5, 6, 7, 8), (6, 10), (7, 13)]

###`Q2:` Multiply Adjacent elements (both side) and take sum of right and lest side multiplication result.


For eg.
```
The original tuple : (1, 5, 7, 8, 10)
Resultant tuple after multiplication :

(1*5, 1*5+5*7, 7*5 + 7*8, 8*7 + 8*10, 10*8) -> (5, 40, 91, 136, 80)

output-(5, 40, 91, 136, 80)
```

In [ ]:
# write your code here
original_tuple=(1, 5, 7, 8, 10)
temp_list = []
for i in range(len(original_tuple)):
  if i == 0:
    temp_list.append(original_tuple[i]*original_tuple[i+1])
  elif i == len(original_tuple)-1:
    temp_list.append(original_tuple[i-1]*original_tuple[i])
  else:
    temp_list.append(original_tuple[i-1]*original_tuple[i]+original_tuple[i]*original_tuple[i+1])
print(tuple(temp_list))

(5, 40, 91, 136, 80)

###`Q3`: Check is tuples are same or not?
Two tuples would be same if both tuples have same element at same index
```
t1 = (1,2,3,0)
t2 = (0,1,2,3)

t1 and t2 are not same
```

In [ ]:
# write your code here
t1 = (1,2,3,0)
t2 = (0,1,2,3)
print(t1==t2)

False

###`Q4`: Count no of tuples, list and set from a list
```
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]

```
`Output:`

```
List-2
Set-2
Tuples-1
```

In [ ]:
from posixpath import sep
# write your code here
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]
list_count=0
tuple_count=0
set_count=0
for item in list1:
  if isinstance(item,tuple):
    tuple_count +=1
  if isinstance(item,list):
    list_count +=1
  if isinstance(item,set):
    set_count +=1

print('List-',list_count)
print('Set-',set_count)
print('Tuples-',tuple_count)

List- 2
Set- 2
Tuples- 1

###`Q5`: Shortlist Students for a Job role
Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.

Show every students record in form of tuples if matches all required criteria.

It is assumed that there will be only one primry skill.

If no such candidate found, print `No such candidate`

`Input:`
```
Enter No of records- 2
Enter Details of student-1
Enter Student name- Manohar
Enter Higher Education- B.Tech
Enter Primary Skill- Python
Enter Year of Graduation- 2022
Enter Details of student-2
Enter Student name- Ponian
Enter Higher Education- B.Sc.
Enter Primary Skill- C++
Enter Year of Graduation- 2020

Enter Job Role Requirement
Enter Skill- Python
Enter Higher Education- B.Tech
Enter Year of Graduation- 2022
```

`Output`
```
('Manohar', 'B.tech', 'Python', '2022')
```

In [ ]:
# write your code here
input_length = int(input("Enter the number of records: "))
student_record=[]
for i in range(input_length):
  student_tuple=()
  print('Enter the details of student-',i+1)
  name=input("Enter student name-")
  education=input("Enter Higher Education-")
  skills=input("Enter Primary Skill-")
  graducation_year=int(input("Enter Year of Graduation-"))
  student_tuple=(name,education,skills,graducation_year)
  student_record.append(student_tuple)
print("Student record are as like: ",student_record)
print("Enter Job Role Requirement-")
job_skill = input("Enter Skill-")
job_education = input("Enter Higher Education-")
grad_year = int(input("Enter Year of Graduation-"))
found = 0
for a,b,c,d in student_record:
  if job_education==b and job_skill==c and grad_year==d:
    print('inside')
    found = 1
    print("Required Details are: ({},{},{},{})".format(a,b,c,d))
    break
if not found:
  print("No such Candidate")

Enter the number of records: 1
Enter the details of student- 1
Enter student name-rama
Enter Higher Education-Bsc
Enter Primary Skill-Math
Enter Year of Graduation-2012
Student record are as like:  [('rama', 'Bsc', 'Math', 2012)]
Enter Job Role Requirement-
Enter Skill-Math
Enter Higher Education-Bsc
Enter Year of Graduation-2012
inside
Required Details are: rama,Bsc,Math,2012

# Set

###`Q1:` Write a program to find set of common elements in three lists using sets.
```
Input : ar1 = [1, 5, 10, 20, 40, 80]
        ar2 = [6, 7, 20, 80, 100]
        ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

Output : [80, 20]
```

In [ ]:
# write your code here
ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]
s1=set();s2=set();s3=set()
s1.update(ar1);s2.update(ar2);s3.update(ar3)
s1 & s2 & s3   # Intersection of sets using & operand

{20, 80}

###`Q2:` Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

`Input:`
```
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
```
`Output:`
```
No of unique vowels-6
```

In [ ]:
# write your code here
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
s1=set(Str1)
vowel_count = 0
for letter in s1:
  if letter in ('A','E','I','O','U','a','e','i','o','u'):
    vowel_count = vowel_count+1
print("No of unique vowels-",vowel_count)

No of unique vowels- 6

### `Q3:` Write a program to Check if a given string is binary string of or not.

A string is said to be binary if it's consists of only two unique characters.

Take string input from user.

```
Input: str = "01010101010"
Output: Yes

Input: str = "1222211"
Output: Yes

Input: str = "Campusx"
Output: No
```

In [ ]:
# write your code here
mystr=input("Enter the input string:")
set_str = set(mystr)
if len(set_str)==2:
  a,b=set_str
  if a=='0' and b=='1':
    print("Yes")
  else:
    print("No")
else:
  print("No")

Enter the input string:111111
No

### `Q4`: find union of n arrays.

**Example 1:**

Input:
```bash
[[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
```

Output:

```bash
[1, 2, 3, 4, 5, 6, 7, 9]
```

In [ ]:
# write your code here
matrix=[[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
s=set()
result=[]
for item in matrix:
  s.update(item)
result.extend(list(s))
result

[1, 2, 3, 4, 5, 6, 7, 9]

### `Q5`: Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using **list-comprehension**.

**Example 1:**

Input:
```bash
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
```

Output:
```bash
[9, 10, 4, 5]
```

**Example 2:**

Input:
```bash
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
```

Output:
```bash
[9, 11, 26, 28]
```

In [ ]:
# write your code here
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
[i for i in lst1 if i in lst2]

[9, 11, 26, 28]

# Dictionary

### `Q1`: Key with maximum unique values

Given a dictionary with values list, extract key whose value has most unique values.

**Example 1:**

Input:

```bash
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
CampusX
```

**Example 2:**

Input:
```bash
test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
Best
```

In [ ]:
# write your code here
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
for key,value in test_dict.items():
  test_dict[key]=len(set(value))
for i in range(3):
  pass

{'CampusX': 5, 'is': 4, 'Best': 3}

### `Q2`: Replace words from Dictionary. Given String, replace it’s words from lookup dictionary.

**Example 1:**

Input:

```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}
```

Output:

```bash
CampusX is the best channel for Data-Science students.
```

**Example 2:**

Input:
```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"good" : "is the best channel", "ds" : "Data-Science"}
```

Output:
```bash
CampusX best for DS students.
```

In [8]:
# write your code here
test_str = 'CampusX best for DS students.'
repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}
res_str=''
for item in test_str.split():
  if item in repl_dict.keys():
    res_str = res_str+' '+repl_dict[item]
  else:
    res_str = res_str +' '+ item
res_str

' CampusX is the best channel for Data-Science students.'

### `Q3`: Convert List to List of dictionaries. Given list values and keys list, convert these values to key value pairs in form of list of dictionaries.

**Example 1:**

Input:
```bash
test_list = ["DataScience", 3, "is", 8]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'DataScience', 'id': 3}, {'name': 'is', 'id': 8}]
```

**Example 2:**

Input:
```bash
test_list = ["CampusX", 10]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'CampusX', 'id': 10}]
```

In [ ]:
# write your code here

### `Q4`: Convert a list of Tuples into Dictionary.

**Example 1:**

Input:
```bash
[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
```

Output:
```bash
{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
```

**Example 2:**

Input:
```bash
[('A', 1), ('B', 2), ('C', 3)]
```

Output:
```bash
{'A': [1], 'B': [2], 'C': [3]}
```

In [10]:
# write your code here
test_tuple_list = [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
res_dict = {}
for a,b in test_tuple_list:
  res_dict[a]=[b]
res_dict

{'akash': [10],
 'gaurav': [12],
 'anand': [14],
 'suraj': [20],
 'akhil': [25],
 'ashish': [30]}

### `Q5`: Sort Dictionary key and values List.

**Example 1:**

Input:

```bash
{'c': [3], 'b': [12, 10], 'a': [19, 4]}
```

Output:

```bash
{'a': [4, 19], 'b': [10, 12], 'c': [3]}
```

**Example 2:**

Input:

```bash
{'c': [10, 34, 3]}
```

Output:

```bash
{'c': [3, 10, 34]}
```

In [24]:
# write your code here
#Note: By Default the dictionary will be soreted based on keys. To do the sorting based on values use lamda function in sorted(iterable,key=lambda x: x[1])
input_dict = {'c': [3], 'b': [100, 10], 'a': [19, 4]}
print("Dictionary sorting based on value: ",dict(sorted(input_dict.items(),key=lambda x:x[1])))
x=dict(sorted(input_dict.items()))
print("By defaul sorting based on Keys:",x)
for key,value in x.items():
  x[key].sort()
print("Desired result a/q: ",x)

Dictionary sorting based on value:  {'c': [3], 'a': [19, 4], 'b': [100, 10]}
By defaul sorting based on Keys: {'a': [19, 4], 'b': [100, 10], 'c': [3]}
Desired result a/q:  {'a': [4, 19], 'b': [10, 100], 'c': [3]}